### ISSUE TITLE
Can't open project configuration

### ISSUE THREAD

**Issue by davidgreisler** [tropyx/NetBeansPuppet#2]
When I try to open the project properties, via "File -> Project Properties (Project name)", I get this exception:
```java.lang.IllegalArgumentException: The designated path Projects/com-tropyx-nb_puppet/Customizer doesn't exist. Cannot create customizer.
	at org.netbeans.spi.project.ui.support.ProjectCustomizer.createCustomizerDialog(ProjectCustomizer.java:255)
	at org.netbeans.spi.project.ui.support.ProjectCustomizer.createCustomizerDialog(ProjectCustomizer.java:213)
	at com.tropyx.nb_puppet.PuppetCustomizerProvider.showCustomizer(PuppetCustomizerProvider.java:40)
	at org.netbeans.modules.project.ui.actions.CustomizeProject.actionPerformed(CustomizeProject.java:151)
	at org.netbeans.modules.project.ui.actions.LookupSensitiveAction.actionPerformed(LookupSensitiveAction.java:174)
	at javax.swing.AbstractButton.fireActionPerformed(AbstractButton.java:1995)
	at javax.swing.AbstractButton$Handler.actionPerformed(AbstractButton.java:2318)
	at javax.swing.DefaultButtonModel.fireActionPerformed(DefaultButtonModel.java:387)
	at javax.swing.DefaultButtonModel.setPressed(DefaultButtonModel.java:242)
	at javax.swing.AbstractButton.doClick(AbstractButton.java:357)```
This makes it impossible to edit project properties.

**Comment by mkleint** [comment]
fixed in recent versions.
