### ISSUE TITLE
Infinate loop when editing case statements

### ISSUE THREAD

**Issue by Conzar** [tropyx/NetBeansPuppet#25]
When I use case statements in my puppet code, the CPU goes to 100% and netbeans becomes unusable.

**Comment by mkleint** [comment]
indeed, a few thread dumps
`
"Editor Parsing Loop (201606280002)" #48 daemon prio=1 os_prio=31 tid=0x00007f85f423c000 nid=0x15d03 runnable [0x00007000060cf000]
   java.lang.Thread.State: RUNNABLE
	at java.util.Arrays$ArrayList.indexOf(Arrays.java:3860)
	at java.util.Arrays$ArrayList.contains(Arrays.java:3868)
	at com.tropyx.nb_puppet.parser.PuppetParser.fastForwardImpl(PuppetParser.java:156)
	at com.tropyx.nb_puppet.parser.PuppetParser.fastForward(PuppetParser.java:145)
	at com.tropyx.nb_puppet.parser.PuppetParser.parseCase(PuppetParser.java:546)
	at com.tropyx.nb_puppet.parser.PuppetParser.fastForwardImpl(PuppetParser.java:269)
	at com.tropyx.nb_puppet.parser.PuppetParser.fastForward(PuppetParser.java:145)
	at com.tropyx.nb_puppet.parser.PuppetParser.parseClassInternal(PuppetParser.java:405)
	at com.tropyx.nb_puppet.parser.PuppetParser.parseClass(PuppetParser.java:376)
	at com.tropyx.nb_puppet.parser.PuppetParser.doParse(PuppetParser.java:81)
	at com.tropyx.nb_puppet.parser.PuppetParser.parse(PuppetParser.java:47)
	at org.netbeans.modules.parsing.impl.TaskProcessor.callParse(TaskProcessor.java:621)
	at org.netbeans.modules.parsing.impl.SourceCache.getResult(SourceCache.java:251)
	at org.netbeans.modules.parsing.impl.TaskProcessor$RequestPerformer.run(TaskProcessor.java:798)
	at org.openide.util.lookup.Lookups.executeWith(Lookups.java:304)
	at org.netbeans.modules.parsing.impl.TaskProcessor$RequestPerformer.execute(TaskProcessor.java:725)
	at org.netbeans.modules.parsing.impl.TaskProcessor$CompilationJob.run(TaskProcessor.java:686)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at org.openide.util.RequestProcessor$Task.run(RequestProcessor.java:1443)
	at org.netbeans.modules.openide.util.GlobalLookup.execute(GlobalLookup.java:68)
	at org.openide.util.lookup.Lookups.executeWith(Lookups.java:303)
	at org.openide.util.RequestProcessor$Processor.run(RequestProcessor.java:2058)
`

`
"Editor Parsing Loop (201606280002)" #48 daemon prio=1 os_prio=31 tid=0x00007f85f423c000 nid=0x15d03 runnable [0x00007000060cf000]
   java.lang.Thread.State: RUNNABLE
	at com.tropyx.nb_puppet.parser.PuppetParser.parseCase(PuppetParser.java:546)
	at com.tropyx.nb_puppet.parser.PuppetParser.fastForwardImpl(PuppetParser.java:269)
	at com.tropyx.nb_puppet.parser.PuppetParser.fastForward(PuppetParser.java:145)
	at com.tropyx.nb_puppet.parser.PuppetParser.parseClassInternal(PuppetParser.java:405)
	at com.tropyx.nb_puppet.parser.PuppetParser.parseClass(PuppetParser.java:376)
	at com.tropyx.nb_puppet.parser.PuppetParser.doParse(PuppetParser.java:81)
	at com.tropyx.nb_puppet.parser.PuppetParser.parse(PuppetParser.java:47)
	at org.netbeans.modules.parsing.impl.TaskProcessor.callParse(TaskProcessor.java:621)
	at org.netbeans.modules.parsing.impl.SourceCache.getResult(SourceCache.java:251)
	at org.netbeans.modules.parsing.impl.TaskProcessor$RequestPerformer.run(TaskProcessor.java:798)
	at org.openide.util.lookup.Lookups.executeWith(Lookups.java:304)
	at org.netbeans.modules.parsing.impl.TaskProcessor$RequestPerformer.execute(TaskProcessor.java:725)
	at org.netbeans.modules.parsing.impl.TaskProcessor$CompilationJob.run(TaskProcessor.java:686)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at org.openide.util.RequestProcessor$Task.run(RequestProcessor.java:1443)
	at org.netbeans.modules.openide.util.GlobalLookup.execute(GlobalLookup.java:68)
	at org.openide.util.lookup.Lookups.executeWith(Lookups.java:303)
	at org.openide.util.RequestProcessor$Processor.run(RequestProcessor.java:2058)
`

**Comment by mkleint** [comment]
https://github.com/tropyx/NetBeansPuppet/commit/61b41a1283bc6728e48dcfd57e29f00e8ebcf13a seemed to fix the problem for me.

**Comment by Conzar** [comment]
great work!  When do you think you will be doing another release?

**Comment by Conzar** [comment]
Thank you!  This works like a charm.  Great work!!!!
